; -- Created with ISN Form Studio 2 for ISN AutoIt Studio -- ;
#include <StaticConstants.au3>
#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#Include <GuiButton.au3>
#include <GuiListView.au3>
#include <GuiTab.au3>
#include <DateTimeConstants.au3>
#include <EditConstants.au3>
#include <ComboConstants.au3>

$frmMain = GUICreate("Customer Record",1024,620,-1,-1,BitOr($WS_MAXIMIZEBOX,$WS_MINIMIZEBOX),-1)
GUISetOnEvent($GUI_EVENT_CLOSE, "_Exit", $frmMain)
$tab = GUICtrlCreatetab(0,0,1024,600,-1,-1)
GuiCtrlSetState(-1,2048)
GUICtrlSetFont(-1,12,400,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,1)
GUICtrlCreateTabItem("Record")
GUICtrlCreateTabItem("Report")
$tabUser = GUICtrlCreateTabItem("USER")
GUICtrlCreateTabItem("")
_GUICtrlTab_SetCurFocus($tab,-1)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,0)&GUICtrlRead ($tab, 1))
$radioUrgent = GUICtrlCreateRadio("Urgent",223,93,80,20,-1,-1)
GUICtrlSetState(-1,BitOr($GUI_CHECKED,$GUI_SHOW,$GUI_ENABLE))
GUICtrlSetResizing(-1,904)
GUICtrlCreateTabItem("")
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,0)&GUICtrlRead ($tab, 1))
$radioAssembly = GUICtrlCreateRadio("Assembly",306,93,80,20,-1,-1)
GUICtrlSetResizing(-1,904)
$editName = GUICtrlCreateInput("",303,137,150,23,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$editPhone = GUICtrlCreateInput("",652,137,150,23,$ES_NUMBER,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$editCity = GUICtrlCreateInput("",303,195,150,23,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$cbProductType = GUICtrlCreateCombo("",489,201,150,21,-1,-1)
GUICtrlSetData(-1,"Laptop|PC|Mobile")
GUICtrlSetResizing(-1,904)
#include <GuiComboBox.au3>


_GUICtrlComboBox_SetCurSel($cbProductType, 0)
$btnCheckSN = GUICtrlCreateButton("Check Model/SN"&@crlf&"",652,196,150,30,-1,-1)
GUICtrlSetOnEvent(-1,"CheckSN")
GUICtrlSetResizing(-1,904)
$editModel = GUICtrlCreateInput("",303,257,150,20,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$editSN = GUICtrlCreateInput("",618,257,184,23,$ES_UPPERCASE,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$gpWarranty = GUICtrlCreateGroup(".",303,306,497,35,-1,-1)
GUICtrlSetResizing(-1,904)
$radioExp = GUICtrlCreateRadio("Expired",329,316,100,20,-1,-1)
GUICtrlSetState(-1,BitOr($GUI_CHECKED,$GUI_SHOW,$GUI_ENABLE))
GUICtrlSetResizing(-1,904)
$radioWithin = GUICtrlCreateRadio("Within",489,316,100,20,-1,-1)
GUICtrlSetResizing(-1,904)
$radioExt = GUICtrlCreateRadio("External",629,316,100,20,-1,-1)
GUICtrlSetResizing(-1,904)
$editError = GUICtrlCreateInput("",303,361,499,23,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$editSolution = GUICtrlCreateInput("",303,417,499,23,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$editDateField = GUICtrlCreateDate("",224,472,186,21,$DTS_SHORTDATEFORMAT,-1)
GUICtrlSetResizing(-1,904)
$btnAdd = GUICtrlCreateButton("ADD",700,470,100,30,-1,-1)
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Name :",218,141,50,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("City :",218,199,85,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Phone Number : 09",498,141,138,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Model :",218,261,85,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Serial Number :",498,261,114,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$lblError = GUICtrlCreateLabel("ERROR :",218,361,84,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$lblSolution = GUICtrlCreateLabel("SOLUTION",218,415,85,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$lblWarranty = GUICtrlCreateLabel("Warranty :",221,316,85,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,1)&GUICtrlRead ($tab, 1))
$editDateFieldReport = GUICtrlCreateDate("",23,73,130,21,$DTS_SHORTDATEFORMAT,-1)
GUICtrlSetResizing(-1,386)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,0)&GUICtrlRead ($tab, 1))
GUICtrlCreateGroup("",157,76,735,448,-1,-1)
GUICtrlSetResizing(-1,904)
Dim $aGroupUrgent[7]

	$aGroupUrgent[0] = $radioExp
	$aGroupUrgent[1] = $radioExt
	$aGroupUrgent[2] = $radioWithin
	$aGroupUrgent[3] = $lblError
	$aGroupUrgent[4] = $lblWarranty
	$aGroupUrgent[5] = $editError
	$aGroupUrgent[6] = $gpWarranty
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,1)&GUICtrlRead ($tab, 1))
$listviewReport = GUICtrlCreatelistview("No.|CustomerName|Phone|City|Type|Warranty|MODEL|SERIALNUMBER|ERROR|SOLUTION|TECHNICIAN|DATE|key",181,40,830,303,$LVS_REPORT,-1)
GUICtrlSetResizing(-1,6)
_GUICtrlListView_SetColumnWidth($listviewReport, 7, 200)
$btnReport = GUICtrlCreateButton("Report",38,163,100,30,-1,-1)
GUICtrlSetResizing(-1,258)
$radioUrgentReport = GUICtrlCreateRadio("Urgent",20,100,50,20,-1,-1)
GUICtrlSetOnEvent(-1,"ToggleRadioWarranty")
GUICtrlSetState(-1,BitOr($GUI_CHECKED,$GUI_SHOW,$GUI_ENABLE))
GUICtrlSetResizing(-1,256)
$radioAssemblyReport = GUICtrlCreateRadio("Assembly",90,100,60,20,-1,-1)
GUICtrlSetOnEvent(-1,"ToggleRadioWarranty")
GUICtrlSetResizing(-1,258)
GUICtrlCreateGroup("Report",10,40,162,191,-1,-1)
GUICtrlSetResizing(-1,256)
$chMobile = GUICtrlCreateCheckbox("Mobile",53,130,60,20,-1,-1)
GUICtrlSetResizing(-1,770)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,2)&GUICtrlRead ($tab, 1))
$btnAddUser = GUICtrlCreateButton("Add",47,162,100,30,-1,-1)
$btnRemoveUser = GUICtrlCreateButton("Remove",47,206,100,30,-1,-1)
$btnShowUser = GUICtrlCreateButton("Show All",47,342,100,30,-1,-1)
$editAddUser = GUICtrlCreateInput("",27,122,150,30,$ES_UPPERCASE,$WS_EX_CLIENTEDGE)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,1)&GUICtrlRead ($tab, 1))
$lblTotalPCs = GUICtrlCreateLabel("Total :",13,204,159,16,-1,-1)
GUICtrlSetFont(-1,10,400,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,256)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,2)&GUICtrlRead ($tab, 1))
$listviewUser = GUICtrlCreatelistview("ID|TECH NAME|URGENT/ASSEMBLY|isAdmin",201,45,602,507,$LVS_SORTASCENDING,-1)
GUISwitch($frmMain,_GUICtrlTab_SetCurFocus($tab,1)&GUICtrlRead ($tab, 1))
$listviewTechQty = GUICtrlCreatelistview("TechName|Qty",10,354,159,201,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,256)
$btnEdit = GUICtrlCreateButton("Edit",40,243,100,30,-1,-1)
GUICtrlSetResizing(-1,258)
$btnDeleteReport = GUICtrlCreateButton("Delete",40,279,100,30,-1,-1)
GUICtrlSetResizing(-1,258)
$gpTotalCount = GUICtrlCreateGroup("",181,360,830,215,-1,-1)
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Urgent",356,370,60,18,-1,-1)
GUICtrlSetFont(-1,10,400,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
GUICtrlCreateLabel("Assembly",766,370,62,18,-1,-1)
GUICtrlSetFont(-1,10,400,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$listviewTotalUrgent = GUICtrlCreatelistview("Laptop|PC|Mobile",221,396,350,102,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
$listviewTotalAssembly = GUICtrlCreatelistview("Laptop|PC|Mobile",618,396,350,102,-1,$WS_EX_CLIENTEDGE)
GUICtrlSetResizing(-1,904)
_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 0, 116)
_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 1, 116)
_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 2, 100)

_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 0, 116)
_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 1, 116)
_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 2, 100)
$lblUrgentTotal = GUICtrlCreateLabel("Total :",290,510,144,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$lblAssemblyTotal = GUICtrlCreateLabel("Total :",703,510,170,15,-1,-1)
GUICtrlSetFont(-1,10,700,0,"MS Sans Serif")
GUICtrlSetBkColor(-1,"-2")
GUICtrlSetResizing(-1,904)
$btnTotalCount = GUICtrlCreateButton("Total Count",251,540,707,30,-1,-1)
GUICtrlSetResizing(-1,904)
_GUICtrlTab_SetCurFocus($tab,0)



#cs
[tab]
type=tab
handle=433
locked=0
resize=1
x=0
y=0
width=1024
height=600
func=
font=MS Sans Serif
fontsize=12
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$tab
text=
pages=3
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=-1
iconindex=
iconlarge=0
textmode=text
order=0
[0x00091D1A]
order=0
[TABPAGE3]
page=3
text=USER
textmode=text
handle=tabUser
[TABPAGE2]
page=2
text=Report
textmode=text
handle=
[TABPAGE1]
page=1
text=Record
textmode=text
handle=
[gui]
Handle_deklaration=default
Handle_deklaration_const=false
title=Customer Record
breite=1024
hoehe=620
style=$WS_MAXIMIZEBOX+$WS_MINIMIZEBOX
exstyle=-1
bgcolour=0xF0F0F0
bgimage=none
handle=$frmMain
parent=
code=
codebeforegui=
xpos=-1
ypos=-1
center_gui=true
title_textmode=normal
isf_include_once=false
only_controls_in_isf=false
const_modus=default
gui_code_in_function=false
gui_code_in_function_name=
gui_event_close=_Exit
gui_event_minimize=
gui_event_restore=
gui_event_maximize=
gui_event_mousemove=
gui_event_primarydown=
gui_event_primaryup=
gui_event_secoundarydown=
gui_event_secoundaryup=
gui_event_resized=
gui_event_dropped=
defaultfont=MS Sans Serif
defaultfontsize=8
[0x0020026A]
type=input
handle=434
locked=0
resize=904
x=303
y=137
width=150
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editName
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
order=2
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000C1C34]
type=input
handle=435
locked=0
resize=904
x=303
y=195
width=150
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editCity
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=4
[0x0004187A]
type=input
handle=436
locked=0
resize=904
x=652
y=137
width=150
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editPhone
text=
state=$GUI_SHOW+$GUI_ENABLE
style=$ES_NUMBER
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=3
[0x00051878]
type=label
handle=437
locked=0
resize=904
x=218
y=141
width=50
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Name :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
order=17
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x0006186C]
type=label
handle=438
locked=0
resize=904
x=218
y=199
width=85
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=City :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=18
[0x0006187C]
type=label
handle=439
locked=0
resize=904
x=498
y=141
width=138
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Phone Number : 09
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=19
[0x00051880]
type=button
handle=440
locked=0
resize=904
x=652
y=196
width=150
height=30
func=CheckSN
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnCheckSN
text=Check Model/SN[BREAK]
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=6
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x00031884]
type=label
handle=441
locked=0
resize=904
x=218
y=261
width=85
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Model :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=20
[0x0004187E]
type=label
handle=442
locked=0
resize=904
x=498
y=261
width=114
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Serial Number :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=21
[0x00031B10]
type=label
handle=443
locked=0
resize=904
x=218
y=361
width=84
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblError
text=ERROR :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=22
[0x00051B14]
type=label
handle=444
locked=0
resize=904
x=218
y=415
width=85
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblSolution
text=SOLUTION
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=23
[0x00041882]
type=input
handle=445
locked=0
resize=904
x=303
y=257
width=150
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editModel
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=7
[0x00041B12]
type=input
handle=446
locked=0
resize=904
x=618
y=257
width=184
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editSN
text=
state=$GUI_SHOW+$GUI_ENABLE
style=$ES_UPPERCASE
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=8
[0x00041B16]
type=input
handle=447
locked=0
resize=904
x=303
y=361
width=499
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editError
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=13
[0x00031B18]
type=input
handle=448
locked=0
resize=904
x=303
y=417
width=499
height=23
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editSolution
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=14
[0x00031B1A]
type=button
handle=449
locked=0
resize=904
x=700
y=470
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnAdd
text=ADD
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=16
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x00031B1C]
type=date
handle=450
locked=0
resize=904
x=224
y=472
width=186
height=21
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editDateField
text=
state=$GUI_SHOW+$GUI_ENABLE
style=$DTS_SHORTDATEFORMAT
exstyle=
bgcolour=
code=
order=15
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x00031B20]
type=listview
handle=451
locked=0
resize=6
x=181
y=40
width=830
height=303
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$listviewReport
text=No.|CustomerName|Phone|City|Type|Warranty|MODEL|SERIALNUMBER|ERROR|SOLUTION|TECHNICIAN|DATE|key
state=$GUI_SHOW+$GUI_ENABLE
style=$LVS_REPORT
exstyle=
bgcolour=
code=_GUICtrlListView_SetColumnWidth($listviewReport, 7, 200)
order=27
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000419C6]
type=group
handle=452
locked=0
resize=904
x=303
y=306
width=497
height=35
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$gpWarranty
text=.
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=9
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x00031B0E]
type=radio
handle=453
locked=0
resize=904
x=329
y=316
width=100
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioExp
text=Expired
state=$GUI_CHECKED+$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=10
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x00041B26]
type=radio
handle=454
locked=0
resize=904
x=489
y=316
width=100
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioWithin
text=Within
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=11
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000419C8]
type=radio
handle=455
locked=0
resize=904
x=629
y=316
width=100
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioExt
text=External
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=12
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000619CA]
type=label
handle=456
locked=0
resize=904
x=221
y=316
width=85
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblWarranty
text=Warranty :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=0
iconindex=
iconlarge=0
textmode=text
order=24
[0x000519CC]
type=group
handle=457
locked=0
resize=256
x=10
y=40
width=162
height=191
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Report
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=31
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319D2]
type=date
handle=458
locked=0
resize=386
x=23
y=73
width=130
height=21
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editDateFieldReport
text=
state=$GUI_SHOW+$GUI_ENABLE
style=$DTS_SHORTDATEFORMAT
exstyle=
bgcolour=
code=
order=25
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319D0]
type=button
handle=459
locked=0
resize=258
x=38
y=163
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnReport
text=Report
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=28
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319CE]
type=radio
handle=460
locked=0
resize=904
x=223
y=93
width=80
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioUrgent
text=Urgent
state=$GUI_CHECKED+$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=0
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000319D4]
type=radio
handle=461
locked=0
resize=904
x=306
y=93
width=80
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioAssembly
text=Assembly
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=1
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000319D6]
type=combo
handle=462
locked=0
resize=904
x=489
y=201
width=150
height=21
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$cbProductType
text=Laptop|PC|Mobile
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=#include <GuiComboBox.au3>[BREAK][BREAK][BREAK]_GUICtrlComboBox_SetCurSel($cbProductType, 0)
order=5
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000319DC]
type=group
handle=463
locked=0
resize=904
x=157
y=76
width=735
height=448
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=Dim $aGroupUrgent[7][BREAK][BREAK]	$aGroupUrgent[0] = $radioExp[BREAK]	$aGroupUrgent[1] = $radioExt[BREAK]	$aGroupUrgent[2] = $radioWithin[BREAK]	$aGroupUrgent[3] = $lblError[BREAK]	$aGroupUrgent[4] = $lblWarranty[BREAK]	$aGroupUrgent[5] = $editError[BREAK]	$aGroupUrgent[6] = $gpWarranty[BREAK]
order=26
tabpage=0
iconindex=
iconlarge=0
textmode=text
[0x000319DE]
type=radio
handle=464
locked=0
resize=256
x=20
y=100
width=50
height=20
func=ToggleRadioWarranty
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioUrgentReport
text=Urgent
state=$GUI_CHECKED+$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=29
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319E0]
type=radio
handle=465
locked=0
resize=258
x=90
y=100
width=60
height=20
func=ToggleRadioWarranty
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$radioAssemblyReport
text=Assembly
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=30
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319E2]
type=listview
handle=466
locked=0
resize=
x=201
y=45
width=602
height=507
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$listviewUser
text=ID|TECH NAME|URGENT/ASSEMBLY|isAdmin
state=$GUI_SHOW+$GUI_ENABLE
style=$LVS_SORTASCENDING
exstyle=
bgcolour=
code=
order=38
tabpage=2
iconindex=
iconlarge=0
textmode=text
[0x000419EC]
type=button
handle=467
locked=0
resize=
x=47
y=162
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnAddUser
text=Add
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=33
tabpage=2
iconindex=
iconlarge=0
textmode=text
[0x000319EA]
type=button
handle=468
locked=0
resize=
x=47
y=206
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnRemoveUser
text=Remove
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=34
tabpage=2
iconindex=
iconlarge=0
textmode=text
[0x000419E8]
type=button
handle=469
locked=0
resize=
x=47
y=342
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnShowUser
text=Show All
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=35
tabpage=2
iconindex=
iconlarge=0
textmode=text
[0x000319EE]
type=input
handle=470
locked=0
resize=
x=27
y=122
width=150
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$editAddUser
text=
state=$GUI_SHOW+$GUI_ENABLE
style=$ES_UPPERCASE
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
order=36
tabpage=2
iconindex=
iconlarge=0
textmode=text
[0x000319F0]
type=button
handle=471
locked=0
resize=258
x=40
y=279
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnDeleteReport
text=Delete
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=41
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319F2]
type=label
handle=472
locked=0
resize=256
x=13
y=204
width=159
height=16
func=
font=MS Sans Serif
fontsize=10
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblTotalPCs
text=Total :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
order=37
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319F4]
type=button
handle=473
locked=0
resize=258
x=40
y=243
width=100
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnEdit
text=Edit
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=40
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319F6]
type=checkbox
handle=474
locked=0
resize=770
x=53
y=130
width=60
height=20
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$chMobile
text=Mobile
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=32
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000319F8]
type=listview
handle=475
locked=0
resize=256
x=10
y=354
width=159
height=201
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$listviewTechQty
text=TechName|Qty
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
order=39
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x000419FE]
type=listview
handle=476
locked=0
resize=904
x=221
y=396
width=350
height=102
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$listviewTotalUrgent
text=Laptop|PC|Mobile
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=
order=45
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x00041A04]
type=button
handle=477
locked=0
resize=904
x=251
y=540
width=707
height=30
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$btnTotalCount
text=Total Count
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=49
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x00031A06]
type=listview
handle=478
locked=0
resize=904
x=618
y=396
width=350
height=102
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$listviewTotalAssembly
text=Laptop|PC|Mobile
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 0, 116)[BREAK]_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 1, 116)[BREAK]_GUICtrlListView_SetColumnWidth($listviewTotalUrgent, 2, 100)[BREAK][BREAK]_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 0, 116)[BREAK]_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 1, 116)[BREAK]_GUICtrlListView_SetColumnWidth($listviewTotalAssembly, 2, 100)
tabpage=1
iconindex=
iconlarge=0
textmode=text
order=46
[0x00041A0C]
type=label
handle=479
locked=0
resize=904
x=356
y=370
width=60
height=18
func=
font=MS Sans Serif
fontsize=10
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Urgent
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
order=43
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x00041BB0]
type=label
handle=480
locked=0
resize=904
x=766
y=370
width=62
height=18
func=
font=MS Sans Serif
fontsize=10
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=
text=Assembly
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=1
iconindex=
iconlarge=0
textmode=text
order=44
[0x000A1A10]
type=group
handle=481
locked=0
resize=904
x=181
y=360
width=830
height=215
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$gpTotalCount
text=
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=
code=
order=42
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x00031A0E]
type=label
handle=482
locked=0
resize=904
x=290
y=510
width=144
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblUrgentTotal
text=Total :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
order=47
tabpage=1
iconindex=
iconlarge=0
textmode=text
[0x00161D1C]
type=label
handle=491
locked=0
resize=904
x=703
y=510
width=170
height=15
func=
font=MS Sans Serif
fontsize=10
fontstyle=700
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lblAssemblyTotal
text=Total :
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=
bgcolour=-2
code=
tabpage=1
iconindex=
iconlarge=0
textmode=text
order=48
#ce
